before_script:
  - pip install codecov
  - pip install -r requirements-test.txt
  
stages:
  - test

py27:
  stage: test
  image: python:2.7
  script:
    - coverage run --source luzfcb_dj_simplelock runtests.py
  tags:
    - py27

py34:
  stage: test
  image: python:3.4
  script:
    - coverage run --source luzfcb_dj_simplelock runtests.py
  tags:
    - py34

py35:
  stage: test
  image: python:3.5
  script:
    - coverage run --source luzfcb_dj_simplelock runtests.py
  tags:
    - py35
