# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueado_em', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('bloqueado_por_user_name', models.CharField(blank=True, editable=False, max_length=500)),
                ('bloqueado_por_full_name', models.CharField(blank=True, editable=False, max_length=500)),
                ('expire_date', models.DateTimeField(verbose_name='expire date')),
                ('app_and_model', models.CharField(blank=True, editable=False, max_length=350)),
                ('model_pk', models.IntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('bloqueado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luzfcb_dj_simplelock_objectlock_bloqueado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='objectlock',
            unique_together=set([('app_and_model', 'model_pk')]),
        ),
    ]
